### ISSUE TITLE
Закомментированного кода быть не должно

### ISSUE THREAD

**Issue by coursar** [dashafromrussia/work2.2#1]
https://github.com/dashafromrussia/work2.2/blob/6e5764e8895cea80b59792e2ea569ef4a090416a/js/app.js#L16-L30

**Comment by dashafromrussia** [comment]
Исправлено в 14fab651dfa13cdac16f7ba398750158be1761a3

**Comment by coursar** [comment]
Если исправлено, закрывайте сразу коммитом
